### PR TITLE
Bundling Core features & Module features

### PR DESCRIPTION
**Pull request by Felli**
I've reworked and bundled both `Core` features and `Module` features in two different directories so that they aren't over ran with folders.

### CODE REVIEW

**Comment by buddh4** [comment]
Think Custom Pages cheatsheet should not be included in the core dev, also not so sure about the emoji cheat sheet, since we plan to replace the richtext soon, also I think something like this should rather be part of a user guide, which is currently not available.

**Comment by Felli** [comment]
I'm fine with that, once the user guide is available we can work on adding it to that then. :+1:

**Comment by Felli** [comment]
I'm going to reopen this just to keep it around so that we can always refer to it for the User guide.

**Comment by Felli** [comment]
@buddh4 I also added a [`cron-job.md`](https://github.com/Felli/humhub-docs/blob/master/admin/cron-jobs.md) for #15, although I believe that it could be updated slightly.

**Comment by buddh4** [comment]
Can't merge since it hase conflicts.

**Comment by Felli** [comment]
I'll close this one and open a new one.

**Pull request closed without merging**
